version: '3.8'
services:
  jira:
    image: atlassian/jira-software:latest
    ports:
      - "8081:8080"
    environment:
      ATL_JDBC_URL: jdbc:postgresql://db:5432/jiradb
      ATL_JDBC_USER: jira
      ATL_JDBC_PASSWORD: jirapassword
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jirapassword
volumes:
  db_data:

